### ISSUE TITLE
Issue with making an engine for yolo trained on a custom dataset

### ISSUE THREAD

**Issue by yousefis** [wang-xinyu/tensorrtx#494]
## Env

- GPU, Xavier NX
- OS,Ubuntu16.04
- Cuda version 10.2
- TensorRT version 7.3.1

## About this repo

- which branch/tag/commit are you using? master
- which model? yolov5, 

## Your problem

I fine tuned yolov5x on a custom dataset with 2 classes, now for creating the engine although I changed the CLASS_NUM in the yololayer.h to 2, when I am trying to run `./yolov5 -s yolov5x_finetuned.wts yolov5x_finetuned.engine x` I get the below error. Any idea will be appropriated.

 `
 [04/20/2021-13:56:41] [E] [TRT] (Unnamed Layer* 475) [Convolution]: kernel weights has count 0 but 6720 was expected
[04/20/2021-13:56:41] [E] [TRT] (Unnamed Layer* 475) [Convolution]: count of 0 weights in kernel, but kernel dimensions (1,1) with 320 input channels, 21 output channels and 1 groups were specified. Expected Weights count is 320 * 1*1 * 21 / 1 = 6720
[04/20/2021-13:56:41] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::482, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5: /home/autofill/Downloads/tensorrtx/yolov5/common.hpp:155: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)
`

**Comment by yousefis** [comment]
was fixed by checking the previous issues

**Comment by wang-xinyu** [comment]
Could be different yolov5 version. You can compare your own model with the official one(which can work) layer by layer.

**Comment by abuelgasimsaadeldin** [comment]
Hi @wang-xinyu I am currently facing this same error with my custom model (everything works fine using the official models), I trained my model using transfer learning with the yolov5s.pt weights. My question is where can I find the *depth_multiple* and *width_multiple* of my custom model?

I have tested out ```sudo ./yolov5 -s yolov5_custom.wts yolov5.engine s``` and also ```sudo ./yolov5 -s yolov5_custom.wts yolov5.engine c 0.33 0.50``` (0.33 & 0.55 are the depth_multiple & with_multiple found in yolov5s.yaml which I used to train my model) but they both return the same error message of ```kernel weights has count 2688 but 32640 was expected```

**Comment by wang-xinyu** [comment]
did you adapt the class num as per the config section in readme?

**Comment by abuelgasimsaadeldin** [comment]
Hi @wang-xinyu, yes I have set the CLASS_NUM in yololayer.h to 2 (number of classes in my custom model) and I still get the error message above.

The thing is, just for testing purpose, I even left it at 2 and tried to serialize the original yolov5s.pt model again which has 80 classes expecting an error message but I still it got ```Build engine successfully``` and the yolov5s.engine was created, not sure what is the problem here..

**Comment by wang-xinyu** [comment]
@abuelgasimsaadeldin did you rebuild cmake and make after setting classnum?

**Comment by abuelgasimsaadeldin** [comment]
@wang-xinyu  I haven't, it works now thank you!

**Comment by kaiven11** [comment]
@abuelgasimsaadeldin  I faced the same problem, how did you fix it?
